// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipping/shipping.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_a93d23e3adb4f3c3, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Shippings            []*Shipping `protobuf:"bytes,1,rep,name=shippings,proto3" json:"shippings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_a93d23e3adb4f3c3, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetShippings() []*Shipping {
	if m != nil {
		return m.Shippings
	}
	return nil
}

type Shipping struct {
	ShippingID           int32    `protobuf:"varint,1,opt,name=shippingID,proto3" json:"shippingID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	PricePerUnit         int32    `protobuf:"varint,4,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shipping) Reset()         { *m = Shipping{} }
func (m *Shipping) String() string { return proto.CompactTextString(m) }
func (*Shipping) ProtoMessage()    {}
func (*Shipping) Descriptor() ([]byte, []int) {
	return fileDescriptor_shipping_a93d23e3adb4f3c3, []int{2}
}
func (m *Shipping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shipping.Unmarshal(m, b)
}
func (m *Shipping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shipping.Marshal(b, m, deterministic)
}
func (dst *Shipping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shipping.Merge(dst, src)
}
func (m *Shipping) XXX_Size() int {
	return xxx_messageInfo_Shipping.Size(m)
}
func (m *Shipping) XXX_DiscardUnknown() {
	xxx_messageInfo_Shipping.DiscardUnknown(m)
}

var xxx_messageInfo_Shipping proto.InternalMessageInfo

func (m *Shipping) GetShippingID() int32 {
	if m != nil {
		return m.ShippingID
	}
	return 0
}

func (m *Shipping) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shipping) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Shipping) GetPricePerUnit() int32 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "main.Request")
	proto.RegisterType((*Response)(nil), "main.Response")
	proto.RegisterType((*Shipping)(nil), "main.Shipping")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	GetShippingProvider(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) GetShippingProvider(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/main.ShippingService/GetShippingProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	GetShippingProvider(context.Context, *Request) (*Response, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_GetShippingProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetShippingProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ShippingService/GetShippingProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetShippingProvider(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShippingProvider",
			Handler:    _ShippingService_GetShippingProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping/shipping.proto",
}

func init() { proto.RegisterFile("shipping/shipping.proto", fileDescriptor_shipping_a93d23e3adb4f3c3) }

var fileDescriptor_shipping_a93d23e3adb4f3c3 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4f, 0x84, 0x30,
	0x10, 0x85, 0x53, 0x17, 0x75, 0x19, 0x75, 0x4d, 0xc6, 0x83, 0x8d, 0x07, 0x43, 0x7a, 0xe2, 0x60,
	0x30, 0x41, 0x0f, 0xfe, 0x00, 0x13, 0xe2, 0x8d, 0x94, 0xf8, 0x03, 0x10, 0x27, 0xda, 0x03, 0x6d,
	0x6d, 0x0b, 0xbf, 0xdf, 0x14, 0x68, 0x74, 0x6f, 0xaf, 0xdf, 0x7b, 0x6d, 0xe7, 0x0d, 0xdc, 0xfa,
	0x6f, 0x65, 0xad, 0xd2, 0x5f, 0x8f, 0x49, 0x54, 0xd6, 0x99, 0x60, 0x30, 0x1b, 0x7b, 0xa5, 0x45,
	0x0e, 0xe7, 0x92, 0x7e, 0x26, 0xf2, 0x41, 0xbc, 0xc0, 0x5e, 0x92, 0xb7, 0x46, 0x7b, 0xc2, 0x07,
	0xc8, 0x53, 0xdc, 0x73, 0x56, 0xec, 0xca, 0x8b, 0xfa, 0x50, 0xc5, 0x0b, 0x55, 0xb7, 0x61, 0xf9,
	0x17, 0x10, 0x33, 0xec, 0x13, 0xc6, 0x7b, 0x80, 0x64, 0xbc, 0xbd, 0x72, 0x56, 0xb0, 0xf2, 0x54,
	0xfe, 0x23, 0x88, 0x90, 0xe9, 0x7e, 0x24, 0x7e, 0x52, 0xb0, 0x32, 0x97, 0x8b, 0x8e, 0x6c, 0xd2,
	0x2a, 0xf0, 0xdd, 0xca, 0xa2, 0x46, 0x01, 0x97, 0xd6, 0xa9, 0x81, 0x5a, 0x72, 0xef, 0xd1, 0xcb,
	0x96, 0x97, 0x8e, 0x58, 0xdd, 0xc0, 0x75, 0xfa, 0xb7, 0x23, 0x37, 0xab, 0x81, 0xf0, 0x19, 0x6e,
	0x1a, 0x0a, 0x89, 0xb6, 0xce, 0xcc, 0xea, 0x93, 0x1c, 0x5e, 0xad, 0xc3, 0x6f, 0x55, 0xef, 0x0e,
	0xe9, 0xb8, 0xd6, 0xfd, 0x38, 0x5b, 0x56, 0xf2, 0xf4, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xf9,
	0x43, 0xbc, 0x2d, 0x01, 0x00, 0x00,
}
